// Code generated by MockGen. DO NOT EDIT.
// Source: product_redis_repository.go

// Package productrepository is a generated GoMock package.
package productrepository

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockProductRedisRepository is a mock of ProductRedisRepository interface.
type MockProductRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRedisRepositoryMockRecorder
}

// MockProductRedisRepositoryMockRecorder is the mock recorder for MockProductRedisRepository.
type MockProductRedisRepositoryMockRecorder struct {
	mock *MockProductRedisRepository
}

// NewMockProductRedisRepository creates a new mock instance.
func NewMockProductRedisRepository(ctrl *gomock.Controller) *MockProductRedisRepository {
	mock := &MockProductRedisRepository{ctrl: ctrl}
	mock.recorder = &MockProductRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRedisRepository) EXPECT() *MockProductRedisRepositoryMockRecorder {
	return m.recorder
}

// CheckStockExists mocks base method.
func (m *MockProductRedisRepository) CheckStockExists(ctx context.Context, productID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStockExists", ctx, productID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckStockExists indicates an expected call of CheckStockExists.
func (mr *MockProductRedisRepositoryMockRecorder) CheckStockExists(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStockExists", reflect.TypeOf((*MockProductRedisRepository)(nil).CheckStockExists), ctx, productID)
}

// DecreaseStock mocks base method.
func (m *MockProductRedisRepository) DecreaseStock(ctx context.Context, productID int64, qty int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseStock", ctx, productID, qty)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseStock indicates an expected call of DecreaseStock.
func (mr *MockProductRedisRepositoryMockRecorder) DecreaseStock(ctx, productID, qty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseStock", reflect.TypeOf((*MockProductRedisRepository)(nil).DecreaseStock), ctx, productID, qty)
}

// DeleteCache mocks base method.
func (m *MockProductRedisRepository) DeleteCache(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCache", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCache indicates an expected call of DeleteCache.
func (mr *MockProductRedisRepositoryMockRecorder) DeleteCache(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCache", reflect.TypeOf((*MockProductRedisRepository)(nil).DeleteCache), ctx, key)
}

// GetJSONCache mocks base method.
func (m *MockProductRedisRepository) GetJSONCache(ctx context.Context, key string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSONCache", ctx, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetJSONCache indicates an expected call of GetJSONCache.
func (mr *MockProductRedisRepositoryMockRecorder) GetJSONCache(ctx, key, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSONCache", reflect.TypeOf((*MockProductRedisRepository)(nil).GetJSONCache), ctx, key, data)
}

// IncreaseStock mocks base method.
func (m *MockProductRedisRepository) IncreaseStock(ctx context.Context, productID int64, qty int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseStock", ctx, productID, qty)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseStock indicates an expected call of IncreaseStock.
func (mr *MockProductRedisRepositoryMockRecorder) IncreaseStock(ctx, productID, qty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseStock", reflect.TypeOf((*MockProductRedisRepository)(nil).IncreaseStock), ctx, productID, qty)
}

// SetJSONCache mocks base method.
func (m *MockProductRedisRepository) SetJSONCache(ctx context.Context, key string, data any, exp time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJSONCache", ctx, key, data, exp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJSONCache indicates an expected call of SetJSONCache.
func (mr *MockProductRedisRepositoryMockRecorder) SetJSONCache(ctx, key, data, exp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJSONCache", reflect.TypeOf((*MockProductRedisRepository)(nil).SetJSONCache), ctx, key, data, exp)
}

// SetStock mocks base method.
func (m *MockProductRedisRepository) SetStock(ctx context.Context, productID int64, initQty int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStock", ctx, productID, initQty)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStock indicates an expected call of SetStock.
func (mr *MockProductRedisRepositoryMockRecorder) SetStock(ctx, productID, initQty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStock", reflect.TypeOf((*MockProductRedisRepository)(nil).SetStock), ctx, productID, initQty)
}
