// Code generated by MockGen. DO NOT EDIT.
// Source: cart_repository.go

// Package cartrepository is a generated GoMock package.
package cartrepository

import (
	context "context"
	reflect "reflect"

	cart "github.com/codepnw/go-starter-kit/internal/features/cart"
	gomock "github.com/golang/mock/gomock"
)

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockCartRepository) AddItem(ctx context.Context, cartID, productID int64, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, cartID, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockCartRepositoryMockRecorder) AddItem(ctx, cartID, productID, quantity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockCartRepository)(nil).AddItem), ctx, cartID, productID, quantity)
}

// FindCartID mocks base method.
func (m *MockCartRepository) FindCartID(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCartID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCartID indicates an expected call of FindCartID.
func (mr *MockCartRepositoryMockRecorder) FindCartID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCartID", reflect.TypeOf((*MockCartRepository)(nil).FindCartID), ctx, userID)
}

// GetCartItems mocks base method.
func (m *MockCartRepository) GetCartItems(ctx context.Context, userID string) ([]*cart.CartItemResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItems", ctx, userID)
	ret0, _ := ret[0].([]*cart.CartItemResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItems indicates an expected call of GetCartItems.
func (mr *MockCartRepositoryMockRecorder) GetCartItems(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItems", reflect.TypeOf((*MockCartRepository)(nil).GetCartItems), ctx, userID)
}

// RemoveItem mocks base method.
func (m *MockCartRepository) RemoveItem(ctx context.Context, cartID, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", ctx, cartID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockCartRepositoryMockRecorder) RemoveItem(ctx, cartID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockCartRepository)(nil).RemoveItem), ctx, cartID, productID)
}
