// Code generated by MockGen. DO NOT EDIT.
// Source: order_repository.go

// Package orderrepository is a generated GoMock package.
package orderrepository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	order "github.com/codepnw/go-starter-kit/internal/features/order"
	gomock "github.com/golang/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// FindOrderDetails mocks base method.
func (m *MockOrderRepository) FindOrderDetails(ctx context.Context, orderID int64) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrderDetails", ctx, orderID)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrderDetails indicates an expected call of FindOrderDetails.
func (mr *MockOrderRepositoryMockRecorder) FindOrderDetails(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrderDetails", reflect.TypeOf((*MockOrderRepository)(nil).FindOrderDetails), ctx, orderID)
}

// InsertOrderItemTx mocks base method.
func (m *MockOrderRepository) InsertOrderItemTx(ctx context.Context, tx *sql.Tx, item order.OrderItemReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrderItemTx", ctx, tx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrderItemTx indicates an expected call of InsertOrderItemTx.
func (mr *MockOrderRepositoryMockRecorder) InsertOrderItemTx(ctx, tx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrderItemTx", reflect.TypeOf((*MockOrderRepository)(nil).InsertOrderItemTx), ctx, tx, item)
}

// InsertOrderTx mocks base method.
func (m *MockOrderRepository) InsertOrderTx(ctx context.Context, tx *sql.Tx, userID string, totalAmount int64, address string) (int64, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrderTx", ctx, tx, userID, totalAmount, address)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InsertOrderTx indicates an expected call of InsertOrderTx.
func (mr *MockOrderRepositoryMockRecorder) InsertOrderTx(ctx, tx, userID, totalAmount, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrderTx", reflect.TypeOf((*MockOrderRepository)(nil).InsertOrderTx), ctx, tx, userID, totalAmount, address)
}
